name: API testing suite

on:
    push:
        branches:
          - master

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CYPRESS_API_KEY: ${{ secrets.CYPRESS_API_KEY }}
      EMAIL: ${{ secrets.EMAIL }}
      USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm install

    - name: Run Cypress Tests
      run: npm run cy:run:test
