name: API testing suite

on:
    push:
        branches:
          - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run API tests
        run: echo "Run your API tests here"